import { Geist, Geist_Mono, Inter  } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter",
});

const aeonik = localFont({
  src: [
    {
      path: "./fonts/OTF/AeonikPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/OTF/AeonikPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-aeonik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aeonik.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}